# Generated by Django 2.1.5 on 2020-08-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelivApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_addr',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
